### PR TITLE
Fixes issue when reading a version 7 .ang file.

### LINKED ISSUE #934: EDAX ANG files from VERSION 7 do not read properly
Trying to read a VERSION 7 .ang file does not properly store the phase information.

### PR DESCRIPTION
**Pull request by imikejackson**
The heart of the issue is that the algorithm keyed off of the "# Phase "
string to know when to begin a new phase. With the newer version = 7 of
.ang files there is an actual comment line that starts with the same key
which then screws up the parsing and creates an invalid phase object which
then overwrites the valid on.

updates #934. Fixes #934

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

### CODE REVIEW

File: Source/EbsdLib/TSL/AngReader.cpp [hunk 1]
```diff
@@ -568,56 +568,67 @@ void AngReader::parseHeaderLine(QByteArray& buf)
   // parsing data for the phase then stick the Phase instance into the header
   // map or stick it into a vector<Phase::Pointer> and stick the vector into
   // the map under the "Phase" key
-  if(word.compare(Ebsd::Ang::Phase) == 0)
+  if(word == Ebsd::Ang::Phase)
   {
     m_CurrentPhase = AngPhase::New();
-    m_CurrentPhase->setPhaseIndex(tokens.at(1).toInt(&ok, 10));
+    int32_t phaseIndex = tokens.at(1).toInt(&ok, 10);
```
Comment (JDuffeyBQ) [inline Source/EbsdLib/TSL/AngReader.cpp]: There's no error checking here for tokens unlike the other cases. Also does the comment version of this line always have a non integer token?

**Review by JDuffeyBQ — APPROVED** [review]
